obstacle_range: 5.5
raytrace_range: 6.0

footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

inflation:
    inflation_radius: 1.0

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

# robot_base_frame: base_scan
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacles_laser:
    observation_sources: scan # Originally laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}


