robot:
  discrete_actions:
    - name: move_forward
      linear: 2.00
      angular: 0.0
    - name: move_backward
      linear: -1.5
      angular: 0.0
    - name: turn_left
      linear: 0.25
      angular: 0.95
    - name: turn_right
      linear: 0.25
      angular: -0.95
    - name: turn_strong_left
      linear: 0.0
      angular: 2.1
    - name: turn_strong_right
      linear: 0.0
      angular: -2.1
    - name: stop
      linear: 0.0
      angular: 0.0
  continuous_actions:
    linear_range: [0, 0.3]
    angular_range: [-2.7,2.7]
