# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

1:
  static: 0
  dynamic: 18
2:
  static: 0
  dynamic: 10
3:
  static: 0
  dynamic: 11
4:
  static: 0
  dynamic: 12
5:
  static: 0
  dynamic: 13
6:
  static: 0
  dynamic: 6
7:
  static: 0
  dynamic: 15
