# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

1:
  static: 6
  dynamic: 0
2:
  static: 8
  dynamic: 0
3:
  static: 10
  dynamic: 0
4:
  static: 12
  dynamic: 0
5:
  static: 14
  dynamic: 0
6:
  static: 18
  dynamic: 0
7:
  static: 20
  dynamic: 0
8:
  static: 24
  dynamic: 0
9:
  static: 30
  dynamic: 0
10:
  static: 34
  dynamic: 0

# 1:
#   static: 0
#   dynamic: 0
# 2:
#   static: 0
#   dynamic: 4
# 3:
#   static: 0
#   dynamic: 8
# 4:
#   static: 0
#   dynamic: 12
# 5:
#   static: 0
#   dynamic: 16
# 6:
#   static: 0
#   dynamic: 20
# 7:
#   static: 0
#   dynamic: 24
# 8:
#   static: 2
#   dynamic: 28
# 9:
#   static: 2
#   dynamic: 32
# 10:
#   static: 2
#   dynamic: 40


