1:
  dynamic_human: 1
  dynamic_robot: 0
  static: 0
2:
  dynamic_human: 3
  dynamic_robot: 0
  static: 0
3:
  dynamic_human: 4
  dynamic_robot: 1
  static: 0
4:
  dynamic_human: 5
  dynamic_robot: 2
  static: 0
5:
  dynamic_human: 6
  dynamic_robot: 3
  static: 0
6:
  dynamic_human: 6
  dynamic_robot: 3
  static: 0
7:
  dynamic_human: 7
  dynamic_robot: 3
  static: 0
8:
  dynamic_human: 8
  dynamic_robot: 4
  static: 0
9:
  dynamic_human: 9
  dynamic_robot: 4
  static: 0
10:
  dynamic_human: 10
  dynamic_robot: 4
  static: 0
11:
  dynamic_human: 11
  dynamic_robot: 5
  static: 0
12:
  dynamic_human: 12
  dynamic_robot: 2
  static: 0
13:
  dynamic_human: 13
  dynamic_robot: 5
  static: 0
14:
  dynamic_human: 14
  dynamic_robot: 6
  static: 0
15:
  dynamic_human: 15
  dynamic_robot: 6
  static: 0
16:
  dynamic_human: 16
  dynamic_robot: 6
  static: 0
17:
  dynamic_human: 16
  dynamic_robot: 6
  static: 0
18:
  dynamic_human: 17
  dynamic_robot: 6
  static: 0
19:
  dynamic_human: 18
  dynamic_robot: 6
  static: 0
20:
  dynamic_human: 19
  dynamic_robot: 6
  static: 0
