#local_costmap
local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.3
  static_map: true
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05
  inflation_layer:
    inflation_radius: 0.4 # 0.0 Localdeki alanlar
